Repository woblerr/authlog_exporter, pull requests merged in 2022-10, with the labels that each got.

#3 allow hiding usernames and ips for reduced load
  README.md
  authlog_exporter.go
  promexporter/exporter.go
  promexporter/exporter_test.go
  promexporter/parser.go
Labels: documentation, enhancement

#4 Switch to alpine base image.
  Dockerfile
  README.md
Labels: bug

#5 Bump to go1.18.
  .github/workflows/build.yml
  .golangci.yml
  .goreleaser.yml
  Dockerfile
  Makefile
  authlog_exporter_test.go
  go.mod
  promexporter/exporter.go
  promexporter/geo.go
Labels: enhancement
